#!/usr/bin/env bash
# Script that configures HAproxy in a load balancer
CONFIG="
frontend myfrontend
    bind *:80
    mode http
    default_backend web_servers
backend web_servers
   balance roundrobin
   server 6362-web-01 44.197.114.77:80 check
   server 6362-web-02 3.233.221.107:80 check
" 
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get -y install haproxy=2.0.\*
# Backup original config file before attempt modifications
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup
printf "%s" "$CONFIG" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
